In [1]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

2.5.1+cu121
True


In [2]:
tensor1 = torch.tensor([[12, 10, 11, 6], [4, 2, 16, 9]])
tensor2 = torch.tensor([[8, 3, 1, 6], [5, 0, 2, 3]])

In [3]:
tensor1 - tensor2

tensor([[ 4,  7, 10,  0],
        [-1,  2, 14,  6]])

In [4]:
(tensor1 + tensor2).size()

torch.Size([2, 4])

In [5]:
# Check if device supports GPU
if torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')
print(device)

cuda


In [6]:
# GPU Tensor
tensor1 = torch.tensor([[12, 10, 11, 6], [4, 2, 16, 9]], device=device)
tensor2 = torch.tensor([[8, 3, 1, 6], [5, 0, 2, 3]], device=device)
mult_tensor = tensor1 * tensor2
print(mult_tensor)

tensor([[96, 30, 11, 36],
        [20,  0, 32, 27]], device='cuda:0')


In [7]:
import numpy as np

In [8]:
list1 = [1,2,3,4,5]
array1 = np.array(list1)
print("Original list:", list1)
print("Numpy array:", array1)
print()

tuple1 = (6,7,8,9,10)
array2 = np.array(tuple1)
print("Original tuple:", tuple1)
print("Numpy array:", array2)
print()

# initialize a tensor from a Python list
tensor_from_list = torch.tensor([1,2,3,4,5])

# initialize a tensor from a tuple
tensor_from_tuple = torch.tensor((6,7,8,9,10))

# initialize a tensor from an ndarray
tensor_from_array=torch.tensor(np.array([11,12,13,14,15]))

print("Tensor from list:", tensor_from_list)
print("Tensor from tuple:", tensor_from_tuple)
print("Tensor from array:",tensor_from_array)

Original list: [1, 2, 3, 4, 5]
Numpy array: [1 2 3 4 5]

Original tuple: (6, 7, 8, 9, 10)
Numpy array: [ 6  7  8  9 10]

Tensor from list: tensor([1, 2, 3, 4, 5])
Tensor from tuple: tensor([ 6,  7,  8,  9, 10])
Tensor from array: tensor([11, 12, 13, 14, 15])


In [9]:
print(type(list1))
print(type(array1))
print(type(tensor_from_list))
print(type(tensor_from_tuple))
print(type(tensor_from_array))

<class 'list'>
<class 'numpy.ndarray'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>


In [10]:
tensor_emp = torch.empty(3,4)
print("tensor_emp :",tensor_emp)
print()

tensor_zeros = torch.zeros(3,4)
print("tensor_zeros :",tensor_zeros)
print()

tensor_ones= torch.ones(3,4)
print("tensor_ones :",tensor_ones)
print()

tensor_emp : tensor([[1.3895e-38, 0.0000e+00, 1.3895e-38, 0.0000e+00],
        [1.5077e-38, 0.0000e+00, 1.5631e+19, 4.3230e-41],
        [1.3978e-03, 4.3231e-41, 1.4667e-32, 0.0000e+00]])

tensor_zeros : tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

tensor_ones : tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])



In [11]:
# Tensor filled with random numbers from a uniform distribution
tensor_rand_un = torch.rand(4,5)
print("tensor_rand_un :",tensor_rand_un)
print()

# Tensor filled with random numbers from a normal distribution
tensor_rand_norm = torch.randn(4,5)
print("tensor_rand_norm :",tensor_rand_norm)
print()

# Tensor filled with random integers generated uniformly
tensor_rand_int = torch.randint(3,10,(7,10))
print("tensor_rand_int :",tensor_rand_int)
print()

tensor_rand_un : tensor([[0.3936, 0.6566, 0.9419, 0.0855, 0.0031],
        [0.8700, 0.6130, 0.1331, 0.4737, 0.3244],
        [0.3829, 0.2748, 0.3345, 0.2372, 0.0590],
        [0.9334, 0.4031, 0.9349, 0.6500, 0.9223]])

tensor_rand_norm : tensor([[-0.4453, -0.8168,  1.5735,  2.4326, -0.1830],
        [-0.9731,  0.6460, -0.1385,  0.0554,  1.6199],
        [-1.1770, -0.0621, -0.2962, -0.8838, -0.9848],
        [ 0.1080,  1.1178,  0.0656,  0.8192, -1.2705]])

tensor_rand_int : tensor([[6, 8, 7, 3, 4, 3, 7, 5, 8, 3],
        [4, 8, 3, 9, 4, 3, 9, 5, 5, 6],
        [6, 9, 8, 6, 9, 6, 5, 5, 7, 8],
        [7, 4, 7, 6, 7, 5, 7, 8, 5, 3],
        [3, 5, 8, 3, 4, 6, 6, 9, 4, 3],
        [9, 9, 3, 9, 3, 3, 8, 5, 9, 7],
        [8, 9, 7, 9, 7, 7, 4, 9, 5, 4]])



In [12]:
# Copy tensor properties
tensor_ones = torch.ones_like(tensor_rand_int)
print(tensor_ones)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])


In [13]:
hey_tensor = torch.tensor([[12, 10, 11, 6], [4, 2, 16, 9], [6, 2, 3, 1]])
hey_tensor.device

device(type='cpu')

In [14]:
hey_tensor.dtype

torch.int64

In [15]:
hey_tensor.shape

torch.Size([3, 4])

In [16]:
hey_tensor.ndim

2

In [17]:
int_tensor= torch.tensor([1,2,3,4,5],dtype=torch.int8)
int_tensor.dtype

torch.int8

In [18]:
float_tensor= torch.tensor([6,7,8,9,10], dtype=torch.float32)
float_tensor.dtype

torch.float32

In [19]:
easy_tensor = torch.tensor([1.1, 5.1])
easy_tensor.dtype

torch.float32

In [20]:
# Cast tensor to new data type
int_tensor = int_tensor.float()
int_tensor.dtype

torch.float32

In [21]:
last_tensor = easy_tensor.to(dtype=torch.float16)
last_tensor.dtype

torch.float16

In [22]:
# Reproducibility
torch.manual_seed(419)
torch.rand(5, 5)

tensor([[0.2833, 0.9795, 0.3945, 0.5815, 0.3220],
        [0.3359, 0.0347, 0.8720, 0.3458, 0.4302],
        [0.7652, 0.5810, 0.9879, 0.9966, 0.4330],
        [0.1219, 0.5452, 0.1211, 0.0743, 0.8370],
        [0.9455, 0.8749, 0.3266, 0.3864, 0.4162]])

In [23]:
# Indexing 1-dim tensor
one_dim_tensor=torch.tensor([11, 6, 4, 8, 2, -5, 9, 3])
print(one_dim_tensor[2])
print(one_dim_tensor[2].item())

tensor(4)
4


In [24]:
one_dim_tensor[2:6]

tensor([ 4,  8,  2, -5])

In [25]:
two_dim_tensor = torch.tensor([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
])

two_dim_tensor[1][3]

tensor(9)

In [26]:
print("first three elements of the 1st row: ",two_dim_tensor[0, 0:3])
print("first four elements of the 2nd row: ",two_dim_tensor[1,0:4])

first three elements of the 1st row:  tensor([1, 2, 3])
first four elements of the 2nd row:  tensor([6, 7, 8, 9])


In [27]:
tensor_criteria = two_dim_tensor[two_dim_tensor<18]
print(tensor_criteria)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])


In [28]:
tensor_criteria.ndim

1

In [29]:
stacked_tensor = torch.stack((two_dim_tensor, two_dim_tensor))
stacked_tensor

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]])

In [30]:
stacked_tensor.shape

torch.Size([2, 4, 5])

In [31]:
first_tensor, second_tensor, third_tensor, fourth_tensor=torch.unbind(two_dim_tensor)
print(first_tensor, second_tensor, third_tensor, fourth_tensor)

tensor([1, 2, 3, 4, 5]) tensor([ 6,  7,  8,  9, 10]) tensor([11, 12, 13, 14, 15]) tensor([16, 17, 18, 19, 20])


In [32]:
# Automatically splits by rows unless otherwise specified (dim=1)
torch.unbind(two_dim_tensor,dim=1)

(tensor([ 1,  6, 11, 16]),
 tensor([ 2,  7, 12, 17]),
 tensor([ 3,  8, 13, 18]),
 tensor([ 4,  9, 14, 19]),
 tensor([ 5, 10, 15, 20]))

In [33]:
# Basic math functions

a=torch.tensor([10, 7, 8, 6, 2])
b=torch.tensor([ 1, 7, 4, 3, 8])

print('adding tensors a and b:', a.add(b))
print('multiplying tensors a and b:', a.mul(b))
print('dividing tensors a and b:', a.div(b))

adding tensors a and b: tensor([11, 14, 12,  9, 10])
multiplying tensors a and b: tensor([10, 49, 32, 18, 16])
dividing tensors a and b: tensor([10.0000,  1.0000,  2.0000,  2.0000,  0.2500])


In [34]:
# Reduction functions (mean function only works when tensor data type is float/complex)
c = torch.tensor([[20., 8., 8., 11.], [3., 19., 14., 3.]])
print('Mean of the tensor c:', torch.mean(c))
print('Max of the tensor c:', torch.max(c))
print('Min of the tensor c:', torch.min(c))
print('Sum of the tensor c:', torch.sum(c))
print('Product of the tensor c:', torch.prod(c))
print('Unique elements of the tensor c:', torch.unique(c))
print('Argmax of the tensor c:', torch.argmax(c))
print('Argmin of the tensor c:', torch.argmin(c))
print('Variance of the tensor c:', torch.var(c))
print('Standard deviation of the tensor c:', torch.std(c))
print('Median of the tensor c:', torch.median(c))
print()

print('Sorted elements of the tensor c:', torch.sort(c))
print()

print('Mode of the tensor c:', torch.mode(c))

Mean of the tensor c: tensor(10.7500)
Max of the tensor c: tensor(20.)
Min of the tensor c: tensor(3.)
Sum of the tensor c: tensor(86.)
Product of the tensor c: tensor(33707520.)
Unique elements of the tensor c: tensor([ 3.,  8., 11., 14., 19., 20.])
Argmax of the tensor c: tensor(0)
Argmin of the tensor c: tensor(4)
Variance of the tensor c: tensor(42.7857)
Standard deviation of the tensor c: tensor(6.5411)
Median of the tensor c: tensor(8.)

Sorted elements of the tensor c: torch.return_types.sort(
values=tensor([[ 8.,  8., 11., 20.],
        [ 3.,  3., 14., 19.]]),
indices=tensor([[1, 2, 3, 0],
        [0, 3, 2, 1]]))

Mode of the tensor c: torch.return_types.mode(
values=tensor([8., 3.]),
indices=tensor([2, 3]))


In [35]:
# Compute the dot product (scalar) of two 1d tensors
first_tensor = torch.tensor([1,2,3])
second_tensor = torch.tensor([4,5,6])

dot_product = torch.matmul(first_tensor,second_tensor)
dot_product

tensor(32)

In [36]:
# Compute the matrix-matrix product (2D tensor) of two 2d tensors
first_2d_tensor = torch.tensor([[1,2,3],[-1,-2,-3]])
second_2d_tensor = torch.tensor([[-1,-2],[4,5],[4,5]])

print(first_2d_tensor.shape)
print(second_2d_tensor.shape)
print()

result_2d_tensor = torch.matmul(first_2d_tensor, second_2d_tensor)
result_2d_tensor

torch.Size([2, 3])
torch.Size([3, 2])



tensor([[ 19,  23],
        [-19, -23]])

In [37]:
# Compute the matrix product of 5 2d tensors
first_ten = torch.randn(2, 3)
second_ten = torch.randn(3, 4)
third_ten = torch.randn(4, 5)
fourth_ten = torch.randn(5, 6)
fifth_ten = torch.randn(6, 7)
torch.linalg.multi_dot((first_ten, second_ten, third_ten, fourth_ten, fifth_ten))

tensor([[ 63.8511, -66.0776,  26.4196, -32.6276,  23.7335,  22.9964, -47.9491],
        [ 24.5874,  -3.4840,   2.8344, -11.6398,  20.5493,   5.2261,  -6.5670]])

In [38]:
# Computing eigenvalues and eigenvectors
A = torch.randn(4,4)
print("Matrix:", A)
eigenvalues, eigenvectors = torch.linalg.eig(A)

print("Eigen Values:", eigenvalues)
print("Eigen Vectors:", eigenvectors)

Matrix: tensor([[-1.4943, -0.9742, -0.1183,  1.3456],
        [-0.8110, -1.2449,  0.8085,  0.6747],
        [ 0.0609,  2.7645, -0.4693,  0.3487],
        [-0.0090, -1.5844, -1.6820, -1.2626]])
Eigen Values: tensor([-2.9067+0.0000j,  0.4365+0.0000j, -1.0004+1.0825j, -1.0004-1.0825j])
Eigen Vectors: tensor([[ 0.4531+0.0000j,  0.5914+0.0000j,  0.6295+0.0000j,  0.6295-0.0000j],
        [ 0.5872+0.0000j, -0.2346+0.0000j,  0.0436+0.1053j,  0.0436-0.1053j],
        [-0.6618+0.0000j, -0.4295+0.0000j,  0.2651-0.3689j,  0.2651+0.3689j],
        [-0.1087+0.0000j,  0.6409+0.0000j,  0.2859+0.5502j,  0.2859-0.5502j]])


In [39]:
# Define tensors
x = torch.autograd.Variable(torch.Tensor([2]),requires_grad=True)
y = torch.autograd.Variable(torch.Tensor([1]),requires_grad=True)
z = torch.autograd.Variable(torch.Tensor([5]),requires_grad=True)

# f(x, y, z) = (x - y)z
a = x - y
f = z * a

print("Final value for Function f = ", f)

#Compute gradients
f.backward()

#Print the gradient value
print("Gradient value for x:",x.grad)
print("Gradient value for y:",y.grad)
print("Gradient value for z:",z.grad)

Final value for Function f =  tensor([5.], grad_fn=<MulBackward0>)
Gradient value for x: tensor([5.])
Gradient value for y: tensor([-5.])
Gradient value for z: tensor([1.])
